CREATE TABLE IF NOT EXISTS users
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email   VARCHAR(255) NOT NULL,
    name    VARCHAR(255) NOT NULL,
    isAdmin BOOLEAN      NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP    NOT NULL,
    event   INTEGER      NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    status  VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events
(
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation        VARCHAR(255)     NOT NULL,
    description       VARCHAR(255)     NOT NULL,
    title             VARCHAR(255)     NOT NULL,
    createdOn         TIMESTAMP        NOT NULL,
    eventDate         TIMESTAMP        NOT NULL,
    publishedOn       TIMESTAMP        NOT NULL,
    paid              BOOLEAN          NOT NULL,
    participantLimit  INTEGER          NOT NULL,
    requestModeration BOOLEAN          NOT NULL,
    views             INTEGER          NOT NULL,
    state             VARCHAR(255)     NOT NULL,
    initiator         INTEGER          NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category          INTEGER          NOT NULL REFERENCES categories (id),
    lat               DOUBLE PRECISION NOT NULL,
    lon               DOUBLE PRECISION NOT NULL
);

CREATE TABLE IF NOT EXISTS categories
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id INTEGER NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       INTEGER NOT NULL REFERENCES events (id) ON DELETE CASCADE
);