services:
  stats-server:
    build: stats/stats-server
    container_name: ewn_stats_service_container
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12343
    depends_on:
      - stats-db

  enm-service:
    build: main-service
    container_name: ewn_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db

  stats-db:
    image: postgres:16.1
    container_name: ewn_stats_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewn_db
    ports:
      - "2323:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ewn